//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tdt_lession12ontap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tdt_TACGIA
    {
        public string Tdt_MaTG { get; set; }
        public string Tdt_TenTacGia { get; set; }
    }
}
